### ISSUE TITLE
Upgrade process

### ISSUE THREAD

**Issue by EvanGoss** [mr-canoehead/network_performance_monitor#11]
I'm currently running [78b6561](https://github.com/mr-canoehead/network_performance_monitor/tree/78b656132200f5168964ba9c51c3a012450c0dd3) and would like to update to the latest code but am not sure I know how to get from A to B. Do the steps below look correct?

1. `git pull` in `~/network_performance_monitor`
2. Follow [Reconfiguring the network interfaces](https://github.com/mr-canoehead/network_performance_monitor/wiki/Reconfiguring-the-network-interfaces) to turn off cron jobs and disable the interface configuration script
3. Reboot
4. `sudo cp -R network_performance_monitor/netperf /opt/netperf`
5. `sudo /opt/netperf/setup.sh`
6. Enable interface configuration script
7. Reboot
8. Enable cron jobs

Thanks,
Evan

**Comment by mr-canoehead** [comment]
The following approach should work (I tried it on my old development RPi which was in a sort of intermediate state between the old version and the new). I added some detail to your steps for future inclusion in the Wiki:
1) Download the latest project files:
`cd ~/network_performance_monitor`
`git pull`
2) Follow [Reconfiguring the network interfaces](https://github.com/mr-canoehead/network_performance_monitor/wiki/Reconfiguring-the-network-interfaces) to turn off cron jobs and disable the interface configuration script
3) Reboot
4) Connect the ISP modem LAN network cable to your router's WAN port
5) Install the required software packages and Python modules (a few have been added):
`sudo ~/network_performance_monitor/install_packages.sh`
6) Copy the new project files:
`sudo cp -R ~/network_performance_monitor/netperf/* /opt/netperf`
 (note the asterisk; without it you'll end up with /opt/netperf/netperf/... instead of overwriting the old files)
7) Run the setup script:
`sudo /opt/netperf/setup.sh`
8) Uncomment the lines in `/etc/rc.local`:
`sudo nano /etc/rc.local`
The lines should look like this:
```
/opt/netperf/tools/fix_log.sh
/usr/bin/python /opt/netperf/configure_interfaces.py
/sbin/runuser -l pi -c 'python /opt/netperf/netperf_db.py &'
```
9) Reboot
10) Re-install the bridge between your router and ISP modem
11) Re-enable your crontab jobs

You should now be able to access the dashboard web page using a web browser, enter the IP address of the interface in the root network namespace of your RPi, e.g; `http://10.1.2.110`

**Comment by EvanGoss** [comment]
Great, thanks for the additional detail and confirmation. I just got it hooked up for the bandwidth monitoring last night (still using the code from April, haven't followed the update steps). I'll give it a little time before updating.

**Comment by farnsaw** [comment]
My upgrade went fairly smoothly, but now I'm getting an error during the configuration of eth0

Configuring ethernet interface eth0
Leaving interface in the root network namespace
Bringing up interface eth0 in root
Configuring IPv4 address for interface eth0
RTNETLINK answers: File exists

ERROR: Unble to assign IPv4 address for interface eth0

My interfaces.json file looks like this:

$ cat interfaces.json
{
        "configure_interfaces" : true,
        "test_exec_namespace" : "root",
        "interfaces" : {
                "wlan0" : {
                        "type" : "wireless",
                        "wpa_supplicant_config" : "/etc/wpa_supplicant/wlan0.conf",
                        "ipv4_addr" : "192.168.86.201",
                        "ipv4_gw" : "192.168.86.1",
                        "namespace" : "ns_wlan0",
                        "alias" : "if_5GHz"
                },
                "wlx801f02aa220e" : {
                        "type" : "wireless",
                        "wpa_supplicant_config" : "/etc/wpa_supplicant/wlx801f02aa220e.conf",
                        "ipv4_addr" : "192.168.1.201",
                        "ipv4_gw" : "192.168.1.1",
                        "namespace" : "ns_wlx801f02aa220e",
                        "alias" : "if_2.4GHz"
                },
                "eth0" : {
                        "type" : "ethernet",
                        "ipv4_addr" : "192.168.1.53",
                        "ipv4_gw" : "192.168.1.1",
                        "namespace" : "root",
                        "alias" : "en0"
                }
        },
        "bandwidth_monitor_bridge" : {
                "configure" : true,
                "namespace" : "bwmonitor",
                "bridge_name" : "bwmonitor",
                "modem_interface" : "enx000acd37bfc9",
                "router_interface" : "enx000acd37bfca"
        }
}


Everything seems to be working correctly so far, at least from internet access perspective, but as to monitoring... I'm not sure as the dashboard is blank.

**Comment by mr-canoehead** [comment]
> My upgrade went fairly smoothly, but now I'm getting an error during the configuration of eth0

I have added a script (`netinfo.sh`) that shows network interface configuration status, it's in the repo now. Please do a `git pull` in `~/network_performance_monitor` to download the script, then run it:

`~/network_performance_monitor/netperf/tools/netinfo.sh > ~/netinfo.txt`

and then email the contents of `~/netinfo.txt` to me at `mr_canoehead@telus.net`

Thanks
Chris

**Comment by mr-canoehead** [comment]
Closing this issue; the upgrade instructions I provided here are obsolete.
