### ISSUE TITLE
speedtest-cli reporting inaccurate results

### ISSUE THREAD

**Issue by christasich** [mr-canoehead/network_performance_monitor#13]
`speedtest-cli` reports inaccurate results for me. I have Comcast gigabit (1000Mbps/40Mbps). Speed tests via a browser (Ookla) show the full speed. However, `speedtest-cli` consistently shows this.

> Latency: ~550ms
> Download: ~300 Mbps
> Upload: ~3 Mbps

I installed the `speedtest` from Okla here - https://www.speedtest.net/apps/cli and I get this

> Latency: ~10ms
> Download: ~800 Mbps
> Upload: ~40 Mbps

Any idea what could be causing the discrepancy? I've [read](https://superuser.com/questions/1434610/speedtest-cli-very-slow-although-network-speed-is-fine) that `speedtest-cli` has been broken and unmanaged. Does anyone else have this problem? Is it possible to use `speedtest` from Ookla instead?

P.S. Great work on this. I saw your post on Reddit and love the idea!

**Comment by mr-canoehead** [comment]
Very interesting, thanks for submitting this issue. This may be a problem on faster networks, I haven't experienced it since I generally deal with home networks that have very slow Internet service (e.g. 25 Mbps down/ 3 Mbps up).

It would certainly be possible to use an alternative speedtest tool, however the output may need to be parsed differently; the Ookla client seems to support json output, not sure if it is the same format as the output of speedtest-cli.

The Ookla client also seems to be closed source; some users may not want to install proprietary software. Perhaps the user could be given a choice during system setup as to which speedtest client is installed and used.

The [EULA](https://www.speedtest.net/about/eula) also raises some interesting questions, as it requires the software to be used "through a command line interface on a personal computer", not sure if running the client programmatically via a Python script meets that definition. It also states that the software may not be installed on "any router, modem, or other non-personal computer device". Not sure if a headless Raspberry Pi would fall into that category or not.

-Chris

**Comment by christasich** [comment]
I dug into it a bit more and it looks like a number of people are experiencing this issue. There are lots of [closed issues](https://github.com/sivel/speedtest-cli/issues?q=is%3Aissue+is%3Aclosed) about it. The dev of speedtest-cli has been relatively unhelpful and pretty dismissive just from reading through the issues. I'm looking into tweaking the Python scripts to use Ookla instead.

**Comment by mr-canoehead** [comment]
I have reached out to Ookla to request clarification regarding the terms of their EULA, want to make sure that integrating their app with the system won't put people in violation of those terms.

**Comment by christasich** [comment]
I haven't looked into the language of the EULA, but [here](https://www.speedtest.net/apps/cli) they specifically mention using it on a Raspberry Pi and automating data collection.

![image](https://user-images.githubusercontent.com/5304026/82708060-f9be6300-9c42-11ea-9e7d-377cd6f4edf8.png)

**Comment by mr-canoehead** [comment]
Well, Ookla has not responded to two requests for clarification regarding the terms in their EULA, so I'm going to say we should go ahead with integrating the Ookla Speedtest CLI with the system based on the language on their website which seems to permit this use case.

I'll modify three areas of the system to support either speedtest client:

1) application settings: add a setting that indicates which client is being used, either `speedtest-cli` or `ookla`

2) package installer: add a prompt asking the user which client to install (open source speedtest-cli, or proprietary Ookla speedtest app), the package installer script will then install the selected client and will update the application setting.

3) testing script: add a query to get the client setting, then execute the appropriate command:
open source client: `speedtest-cli --json`
Ookla client: `speedtest --format=json`
modify the parsing logic to extract data from the JSON response based on the client type (the JSON responses generated by the clients have different formats).

I'll create a branch for these changes, guessing they should be complete early next week. I'll do some testing on my system, and will then ask you to test the changes with your faster ISP connection. I'll provide migration steps so that you don't have to reinstall the whole system from scratch to try out the changes. If all the testing is successful I'll then merge the changes into the master branch.

Cheers,
Chris

**Comment by christasich** [comment]
Sounds great. I've already modified my local python script to use the Ookla client and it works well. I can easily revert though when you push the new changes. Thanks for looking into this!

**Comment by christasich** [comment]
Also, check out this project if you haven't seen it already. It uses the Ookla client.

https://github.com/brennentsmith/internet-speed-logger

**Comment by mr-canoehead** [comment]
The changes to support the Ookla speedtest client are complete, I have pushed them to the `ookla` branch of the project. I've added the steps to patch your system below, I'm assuming that you have the Ookla Speedtest CLI package installed.

To verify that the package is installed:
`dpkg -s speedtest | grep 'Status'`
output should be:
`Status: install ok installed`

Note that the open source `speedtest-cli` package also has a `speedtest` command, so it's best to uninstall it to avoid executing the wrong client:
`sudo apt remove speedtest-cli`

To patch your system:

1) clone the `ookla` branch of the project:
`git clone -b ookla https://github.com/mr-canoehead/network_performance_monitor.git`

2) copy the updated scripts:
`sudo cp ~/network_performance_monitor/netperf/{netperf_settings.py, test_network.py, setup.sh} /opt/netperf`

3) add the new speedtest client setting to the config file:
`sudo /opt/netperf/netperf_settings.py --set speedtest_client --value ookla`

That should do it, the next time your `test_network.py isp` crontab job runs it will execute the modified script.

Let me know if you encounter any issues or have any questions!

Thanks,
Chris

**Comment by christasich** [comment]
Awesome! It works. One small change to step 2 of the patch in case someone else comes across this before you implement it in the master branch. It should be...

2. copy the updated scripts:
`sudo cp ~/network_performance_monitor/netperf/{netperf_settings.py,test_network.py,setup.sh} /opt/netperf`

The spaces in the brackets are registered as part of the name of the file so that command can't find the files.

**Comment by mr-canoehead** [comment]
Great! Thanks for testing out the changes. I'll do one more full install to make sure I haven't broken the open source `speedtest-cli` option, will merge to the master branch when that is done.

I have corrected the patch instructions above per your note.

Cheers,
Chris

**Comment by mr-canoehead** [comment]
Users can now choose which speedtest client to use - open source speedtest-cli, or proprietary Ookla Speedtest CLI.
