### ISSUE TITLE
Feature Request: Choose port for Network Performance Monitor web service

### ISSUE THREAD

**Issue by christasich** [mr-canoehead/network_performance_monitor#16]
Would it be possible to have the option during the initial configuration to choose the port that the Network Performance Monitor web service is served on? I had other services running on my RPi4 at port 80. I was able to change the other service's port within its configuration files. I'm a bit unfamiliar with Nginx so I didn't play with the NPM web service, but I think I would only need to change the top two lines of `/opt/netperf/dashboard/config/nginx/netperf-dashboard`.

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
```

This seems like it could be a simple addition, but obviously low priority if it can indeed be manually changed in the top line of `netperf-dashboard`.

**Comment by mr-canoehead** [comment]
It should be fairly straightforward to allow the user to select a port for the nginx web server during the setup process. For now it can be done manually; my system is now serving the dashboard web page on port 8080, I made the following changes to `/etc/nginx/sites-available/netperf-dashboard`:

```
listen 8080 default_server;
listen [::]:8080 default_server;
```
At first this didn't work (blank charts, no data), but after some googling I discovered that the `proxy_set_header` setting in the `location /socket.io/` section needed to be modified, the corrected line is:
```
proxy_set_header        Host                    $http_host;
```
After changing these three lines and restarting the nginx service the dashboard web page should be accessible via `http://server_ip:8080` where `server_ip` is the ip address of the interface in the root network namespace.

Since the `$http_host` value works when using port 80 as well I'll make this the default setting in the config file that is included with the project.

I'll add a section to the Wiki documenting how to run nginx on a non-standard port, in the near future I'll modify the setup script to prompt the user.

**Comment by mr-canoehead** [comment]
modified the setup.sh script, it now prompts the user to select a port for the web server (standard port 80 as the default option, alternate port 8080, or custom user specified port). If a non-standard port is chosen the setup script modifies the nginx site configuration file to set the port value.
