### ISSUE TITLE
Scriptname typo on wiki/Reconfiguring-the-network-interfaces

### ISSUE THREAD

**Issue by EvanGoss** [mr-canoehead/network_performance_monitor#6]
`sudo /opt/netperf/setup_interfaces.py` should be `sudo /opt/netperf/setup_interfaces.sh`

I would have submitted a pull request but I'm not sure if there's a way to fork the wiki repo.

**Comment by mr-canoehead** [comment]
Thanks, I have corrected the command.
Unfortunately GitHub doesn't have a good way for managing Wiki changes; there's no way to fork a Wiki and issue pull requests for changes made on the fork. Collaborators have write-access to the Wiki and so can make changes directly, but since there's no notification process for Wiki edits I won't get notified of the changes. For now I think the best way to manage Wiki edits is via the issue tracking system, i.e. submitting an issue as you did.

Cheers,
Chris
