### ISSUE TITLE
How to validate support for Network Namespaces

### ISSUE THREAD

**Issue by EvanGoss** [mr-canoehead/network_performance_monitor#8]
Apologies if this is more a support question than valid issue, but perhaps some clarification could be added to the docs regarding confirmation of support for network namespaces for a given network adapter.

I've got a Pi 4B and a TP-Link UE330 and it appears that everything is working as it should using the onboard wifi adapter for 2.4GHz and the UE330 as the speed test interface.  I see that they are both have a namespace applied in /opt/netperf/config/interfaces.json.  What criteria should I be using to confirm that they both have valid network namespace support?

**Comment by mr-canoehead** [comment]
I agree, I should add more info to the Wiki about this. I'll leave this issue open until I've done that.

For Ethernet interfaces like the TP-Link UE330 I haven't found a way to determine if they (or rather their Linux drivers) support network namespaces. The interface configuration script `/opt/netperf/configure_interfaces.py` that runs at boot time will print an error message if it fails to move the interface to its network namespace.

For wireless network interfaces like the integrated WiFi adapter on the RPi we can use the `iw list` command:

First, list the wireless interfaces - this gives us the physical name of each interface:

`iw dev`

e.g. the integrated WiFi interface on my RPi 3B+ has the physical name `phy0`

Then, use the `iw list` command to list the properties of the wireless interfaces:

`iw list`

The output of this command includes the interfaces' physical names and their capabilities. Look for the following in the output:

```
Supported commands:
...
* set_wiphy_netns
...
```
If `set_wiphy_netns` is listed, the adapter's driver supports switching network namespaces. If it doesn't appear, the driver doesn't support the command and the interface will be left in the default (root) network namespace.

Please feel free to keep submitting issues like this; it's early days in this project's life cycle, and having technically adept users such as yourself helping with 'shaking out the bugs' is great. If you'd like to discuss a topic that might not be suitable as an issue, you can email me directly at: mr_canoehead@telus.net

-Chris

**Comment by EvanGoss** [comment]
Okay, I can confirm that `iw list` shows `set_wiphy_netns` for the onboard wifi of the Pi 4B.

Is there something for USB wired ethernet NICs or is support pretty universal in that world?

**Comment by mr-canoehead** [comment]
I haven't found equivalent commands for checking if a wired Ethernet interface supports switching network namespaces, anecdotally it seems that most do support it.

It would be possible to write a script to test an interface, the script would:
- add a 'test' network namespace
- attempt to move the interface to that network namespace (recording the return code that indicates success / failure)
- move the interface back to the default network namespace if it was moved successfully
- delete the 'test' network namespace
- report to the user whether or not the interface supports switching network namespaces

This script would need to be run from the console though, since a possible side-effect is loss of network connectivity (if the user tests an interface that is hosting their ssh connection).

**Comment by mr-canoehead** [comment]
I have updated the 'Supported network adapters' page in the Wiki to include the commands to check if a wireless network adapter supports Network Namespaces.
